# NumPy Practice Notebook

This notebook contains a series of practice problems to help you understand and apply core concepts in NumPy.

---

## 🧩 1. Array Creation
**Question:** Create the following arrays using NumPy:
1. A 1D array with numbers from 0 to 9
2. A 2D array of shape (3, 3) filled with zeros
3. A 2D array of shape (2, 4) filled with ones
4. A 3x3 identity matrix


---


In [2]:
import numpy as np
arr_1d=np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
arr_2d=np.zeros((3, 3))
arr_3 =np.ones((2, 4))
arr_4 =np.identity(3)



## 🧪 2. Array Inspection
**Question:** Given a NumPy array `arr`, print:
1. Its shape
2. Its data type
3. The number of dimensions
4. The total number of elements

```python
arr = np.array([[1, 2, 3], [4, 5, 6]])

```

---


In [3]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr.shape
arr.ndim
arr.dtype
arr.size


6


## 🔍 3. Indexing and Slicing
**Question:** Using the array below, do the following:
1. Slice the first two rows
2. Get the last column
3. Extract the element in the second row and third column
4. Reverse the rows

```python
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

```


In [4]:
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

In [6]:
arr[:2]

array([[10, 20, 30],
       [40, 50, 60]])

In [9]:
arr[:3,2]

array([30, 60, 90])

In [12]:
arr[1,2]

np.int64(60)

In [13]:
arr[::-1]

array([[70, 80, 90],
       [40, 50, 60],
       [10, 20, 30]])


---

## 🔁 4. More Slicing Practice
**Question:**
Given the array below, extract:
1. All even numbers
2. The second and third rows
3. The last two columns
4. A subarray containing the middle 2x2 block

```python
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])

```


In [20]:
import numpy as np

arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])

even_numbers = arr[arr % 2 == 0]
print("Even numbers:\n", even_numbers)

rows_2_3 = arr[1:3, :]
print("\nSecond and third rows:\n", rows_2_3)

last_two_cols = arr[:, -2:]
print("\nLast two columns:\n", last_two_cols)

middle_block = arr[1:3, 1:3]
print("\nMiddle 2x2 block:\n", middle_block)


Even numbers:
 [ 2  4  6  8 10 12 14 16]

Second and third rows:
 [[ 5  6  7  8]
 [ 9 10 11 12]]

Last two columns:
 [[ 3  4]
 [ 7  8]
 [11 12]
 [15 16]]

Middle 2x2 block:
 [[ 6  7]
 [10 11]]



---

## ➕ 5. Arithmetic Operations
**Question:** Perform the following using NumPy arrays:
1. Add two arrays element-wise
2. Multiply two arrays element-wise
3. Raise all elements of an array to the power of 2

```python
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

```

---


In [23]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr1+arr2

array([5, 7, 9])

In [24]:
arr1*arr2

array([ 4, 10, 18])

In [25]:
arr1**2

array([1, 4, 9])


## 📏 6. Broadcasting
**Question:** Use broadcasting to:
1. Add a 1D array to each row of a 2D array
2. Multiply each row of a 2D array by a 1D array
3. Subtract a scalar from each element in an array
4. Add a column vector to each column of a matrix

```python
A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([10, 20, 30])
C = np.array([[1], [2]])

```


In [26]:
import numpy as np
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([10, 20, 30])
C = np.array([[1], [2]])

In [27]:
A+B

array([[11, 22, 33],
       [14, 25, 36]])

In [30]:
A*B

array([[ 10,  40,  90],
       [ 40, 100, 180]])

In [32]:
A-5

array([[-4, -3, -2],
       [-1,  0,  1]])

In [31]:
A+C

array([[2, 3, 4],
       [6, 7, 8]])


---

## 🔁 7. More Broadcasting Practice
**Question:** Try these:
1. Add a 1D array of shape (4,) to a 2D array of shape (3,4)
2. Multiply a (3,1) column array to a (1,4) row array and observe the shape
3. Add a scalar to the entire array

```python
A = np.arange(12).reshape(3, 4)
B = np.array([100, 200, 300, 400])
C = np.array([[2], [3], [4]])

```


In [33]:
A+B

array([[11, 22, 33],
       [14, 25, 36]])

In [34]:
C*B

array([[10, 20, 30],
       [20, 40, 60]])

In [35]:
A+10

array([[11, 12, 13],
       [14, 15, 16]])


---

## 🔃 8. Reshaping and Flattening
**Question:**
1. Reshape a 1D array of 12 elements into a 3x4 matrix
2. Flatten a 2D array into a 1D array

```python
arr = np.arange(12)

```


In [40]:
arr = np.arange(12)
reshaped=arr.reshape(3, 4)
reshaped

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [41]:
reshaped.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])


---

## 🔗 9. Stacking and Splitting
**Question:** Stack and split arrays:
1. Stack two (2, 2) arrays vertically and horizontally
2. reshape a (4, 4) array into array of shape (2, 8)


---


In [42]:
arr1 = np.array([[1, 2],
                 [3, 4]])
arr2 = np.array([[5, 6],
                 [7, 8]])
v_stack = np.vstack((arr1, arr2))
print("\n1. Vertically stacked:\n", v_stack)

h_stack = np.hstack((arr1, arr2))
print("\nHorizontally stacked:\n", h_stack)
arr_big = np.arange(16).reshape(4, 4)
print("\nOriginal 4x4 array:\n", arr_big)

reshaped = arr_big.reshape(2, 8)
print("\nReshaped to 2x8:\n", reshaped)


1. Vertically stacked:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

Horizontally stacked:
 [[1 2 5 6]
 [3 4 7 8]]

Original 4x4 array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Reshaped to 2x8:
 [[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]



## 🧠 10. Boolean Masking
**Question:**
Given an array:
1. Select all elements > 10
2. Replace all even numbers with -1

```python
arr = np.array([[5, 10, 15], [20, 25, 30]])

```


In [45]:
arr = np.array([[5, 10, 15], [20, 25, 30]])
greater_than_10 = arr[arr > 10]
print("\n1. Elements greater than 10:\n", greater_than_10)

arr[arr % 2 == 0] = -1
print("\n2. Array after replacing even numbers with -1:\n", arr)



1. Elements greater than 10:
 [15 20 25 30]

2. Array after replacing even numbers with -1:
 [[ 5 -1 15]
 [-1 25 -1]]



---

## 🧮 11. Aggregation
**Question:** Calculate:
1. Sum of all elements
2. Mean of each column
3. Max value in each row
4. Standard deviation of the array

```python
arr = np.array([[1, 2, 3], [4, 5, 6]])

```


In [46]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
total_sum = np.sum(arr)
mean_columns = np.mean(arr, axis=0)
max_rows = np.max(arr, axis=1)
std_dev = np.std(arr)
print("1. Sum of all elements:", total_sum)
print("2. Mean of each column:", mean_columns)
print("3. Max value in each row:", max_rows)
print("4. Standard deviation of the array:", std_dev)

1. Sum of all elements: 21
2. Mean of each column: [2.5 3.5 4.5]
3. Max value in each row: [3 6]
4. Standard deviation of the array: 1.707825127659933



---

## 🧲 12. Dot Product and Matrix Multiplication
**Question:**
1. Multiply two matrices using `np.dot`

```python
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])

```


In [47]:
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])

result = np.dot(A, B)

print(result)

[[19 22]
 [43 50]]



---

## 🔢 13. Random Numbers
**Question:**
1. Generate a 2x3 array of random numbers between 0 and 1
2. Generate 10 random integers between 50 and 100



In [48]:
arr1 = np.random.rand(2, 3)

arr2 = np.random.randint(50, 101, size=10)  # 101 is exclusive

print("Random 2x3 array between 0 and 1:\n", arr1)
print("\nRandom 10 integers between 50 and 100:\n", arr2)

Random 2x3 array between 0 and 1:
 [[0.50322873 0.98551775 0.83360695]
 [0.81279143 0.81843884 0.01012364]]

Random 10 integers between 50 and 100:
 [55 62 62 72 79 53 55 55 89 63]



---

## 📐 14. Linear Algebra
**Question:**
1. Find the rank of a matrix
2. Compute the inverse of a matrix
3. Compute the determinant of a matrix



---


In [49]:

A = np.array([[1, 2, 3],
              [0, 1, 4],
              [5, 6, 0]])

rank = np.linalg.matrix_rank(A)

inverse = np.linalg.inv(A)

determinant = np.linalg.det(A)

print("Matrix:\n", A)
print("\nRank of the matrix:", rank)
print("\nInverse of the matrix:\n", inverse)
print("\nDeterminant of the matrix:", determinant)


Matrix:
 [[1 2 3]
 [0 1 4]
 [5 6 0]]

Rank of the matrix: 3

Inverse of the matrix:
 [[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]

Determinant of the matrix: 0.9999999999999964



## ⭐ Bonus Challenge
**Question:**
Given a 2D array of shape (6, 6), extract all 3x3 submatrices (using slicing) and store them in a list.




---

Happy coding! 🎯
